#!/bin/sh
bspc config window_gap 20
bspc config border_width 0
bspc config gapless_monocle true
bspc config borderless_monocle true
bspc config single_monocle true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
bspc config initial_polarity first_child
bspc monitor -d monocle
bspc desktop -l monocle
